%YAML:1.0
cam0:
    T_cam_imu:
      - [0.004637443777465944, -0.9999689450133201, 0.006372058078592424, 0.026702366520489827]
      - [-0.01861391778756205, -0.00645734275096882, -0.9998058935559406, -0.002847338916058711]
      - [0.9998159911602771, 0.004517934654532263, -0.018643285296552625, -0.11960054240440089]
      - [0.0, 0.0, 0.0, 1.0]
    cam_overlaps: [0]
    camera_model: pinhole
    distortion_coeffs: [-0.03290300443768501, 0.03494822978973389, -0.00016445788787677884, -2.1918178390478715e-05]
    distortion_model: radtan
    intrinsics: [406.9036560058594, 406.8845520019531, 422.4888610839844, 234.09555053710938]
    resolution: [848, 480]
    rostopic: /camera/color/image_raw

cam1:
    T_cam_imu:
      - [0.09857466510548239, 0.9793403057104775, -0.17656613777915797, -0.0060049120768834174]
      - [0.6016791201560514, -0.1999801314960087, -0.773298249949576, -0.20144526536265153]
      - [-0.7926318639618141, -0.030008542412880868, -0.6089615879632084, 0.5929313416861246]
      - [0.0, 0.0, 0.0, 1.0]
    cam_overlaps: [0]
    camera_model: pinhole
    distortion_coeffs: [-0.25437875807687377, 0.04361703030584596, 0.00029891528087840633, -0.0032503331097878114]
    distortion_model: radtan
    intrinsics: [465.5228134137574, 464.6623277857706, 675.5604618914683, 341.8741376146657]
    resolution: [1280, 720]
    rostopic: /camera/image_raw
  