cam0:
  T_cam_imu:
    - [0.004072727552259958, -0.999978426860902, 0.0051535136638649615, 0.028282863679341963]
    - [-0.020385766749733747, -0.005235510680078326, -0.999778480435515, -0.0004786105005355009]
    - [0.999783893351115, 0.0039667670359331275, -0.020406649773348995, -0.12045193016427451]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.03290300443768501, 0.03494822978973389, -0.00016445788787677884, -2.1918178390478715e-05]
  distortion_model: radtan
  intrinsics: [368.2386169433594, 368.2213439941406, 318.14288330078125, 234.65118408203125]
  resolution: [640, 480]
  rostopic: /camera/color/image_raw
  timeshift_cam_imu: -0.025279461378071875