%YAML:1.0

cam0:
  T_imu_cam:
    - [0.00463744, -0.99996895, 0.00637206, 0.02670237]
    - [-0.01861392, -0.00645734, -0.99980589, -0.00284734]
    - [0.99981599, 0.00451793, -0.01864329, -0.11960054]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.03290300443768501, 0.03494822978973389, -0.00016445788787677884, -2.1918178390478715e-05]
  distortion_model: radtan
  intrinsics: [406.9036560058594, 406.8845520019531, 422.4888610839844, 234.09555053710938]
  resolution: [848, 480]
  rostopic: /camera/color/image_raw