%YAML:1.0
cam0:
    T_cam_imu:
      - [0.004637443777465944, -0.9999689450133201, 0.006372058078592424, 0.026702366520489827]
      - [-0.01861391778756205, -0.00645734275096882, -0.9998058935559406, -0.002847338916058711]
      - [0.9998159911602771, 0.004517934654532263, -0.018643285296552625, -0.11960054240440089]
      - [0.0, 0.0, 0.0, 1.0]
    cam_overlaps: [0]
    camera_model: pinhole
    distortion_coeffs: [-0.03290300443768501, 0.03494822978973389, -0.00016445788787677884, -2.1918178390478715e-05]
    distortion_model: radtan
    intrinsics: [406.9036560058594, 406.8845520019531, 422.4888610839844, 234.09555053710938]
    resolution: [848, 480]
    rostopic: /camera/color/image_raw
  